### PR TITLE
Improve german translation.

### PR DESCRIPTION
**Pull request by gregorfischer**
Improve german translation.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
@gregorfischer thanks! I don't speak a word of German, so I'll trust you on this!

**Comment by gregorfischer** [comment]
Thanks for your trust. 👍

The first try was a little clumsy, as I did not know where all the translations would be used. Seeing it in action helped... 

By the way: I don't know how to build Projectify myself from the repository in order to test changes before committing. Are there any instructions?

**Comment by NicolasPetton** [comment]
@gregorfischer I added a section to the readme, please tell me if something's missing.

**Comment by gregorfischer** [comment]
That's great, thanks! Should have figured that our by myself though...

Some thoughts:
* a straight `npm run serve` on a clean checkout gives a TW with _Projectify_, but without the _Notebook_ theme. 
* `package.json` does not include scripts for most languages (like `de`)
* Straight forward adding the script for `de` does not work, I assume I would have to add some required file in `editions`
* the french script resolves to a TW even with core-TW-language-plugin -- nice! That would be great for other languages as well
* serving `empty` resolves in a TW with a notebook theme, but no projectify-plugin.
* `npm run build-empty` works. You should add a hint for the output path in `editions\empty\output`. Unfortunately the resulting file seams to be missing the projectify-plugin, too. `build-empty-fr` has the same result.
* the `build-demo` results in an error 

I'm not sure, but as discussed in some issue (or discussion), it looks like you recently removed the `highlighter`-plugin. Maybe that introduced some build problems? Or did I miss something?

**Comment by NicolasPetton** [comment]
> package.json does not include scripts for most languages (like de)

I haven't added editions for all lanuages yet.

> serving empty resolves in a TW with a notebook theme, but no projectify-plugin.

Thanks, that was a bug due to a faulty symlink, I've pushed a fix.

> the build-demo results in an error

Could you paste the output?

**Comment by NicolasPetton** [comment]
> a straight npm run serve on a clean checkout gives a TW with Projectify, but without the Notebook theme.

That's because I'm developing & testing Projectify with the vanilla theme, not Notebook. I want Projectify to work well with the default TW settings.

**Comment by NicolasPetton** [comment]
@gregorfischer Are you using Windows? It looks like Git support for symlinks in Windows is not quite there: https://github.com/git-for-windows/git/wiki/Symbolic-Links

I think I'll go for another approach then and use env variables instead.

**Comment by NicolasPetton** [comment]
@gregorfischer I've changed the approach to avoid symlinks for windows compatibility, and also added a new empty edition in German.

Just make sure to run `npm install` again after pulling.

Cheers,
Nico

**Comment by gregorfischer** [comment]
Hi Nicolas (@NicolasPetton),
yes, I was working on Windows for this. While Windows has "some kind" of support of symlinks, at least it didn't work here or in git in general. Anyway, our changes have fixed that 😃! I can now build all editions. 

Some notes:
* ✔️ The error for `build-demo` is gone.
* 🐛 The build for `build-empty-de` yields the right content, but in a file `emtpy-nl-NL.html`. That's obviously because of a copy/paste-error in `editions/emtpy-de-DE/tiddlywiki.info`.
* 🐛 Using multiple `;`-separated commands in `package.json` like for `build-empty-all` does not work (on Windows?). Looks like this is not executed in a real shell, but instead `npm run` seams to take each following param literally (e.g. `build-empty;` - including the `;`).

Thanks for your help and great work!
Gregor.

**Comment by NicolasPetton** [comment]
>  The build for build-empty-de yields the right content, but in a file emtpy-nl-NL.html. 

Thanks, I'll fix that :)

> bug Using multiple ;-separated commands in package.json like for build-empty-all does not work (on Windows?). Looks like this is not executed in a real shell, but instead npm run seams to take each following param literally (e.g. build-empty; - including the ;).

That's a shame. I don't have a windows box to try and fix this, but I'll see if I can find a workaround.

**Pull request merged**
